#pragma once

#include <string_view>

// Wall-E's own sounds (generated by make_sounds.py, embedded from this board folder).
namespace walle_sounds {

std::string_view WakeChirp();
std::string_view Shutter();
std::string_view Tone();
std::string_view Alarm();

}  // namespace walle_sounds
